### ISSUE TITLE
paper-horizontal-stepper clips content area

### ISSUE THREAD

**Issue by dantman** [Zecat/paper-stepper#15]
The `#slideshow` in `<paper-horizontal-stepper>` has `overflow: hidden;` set on it instead of `overflow: auto;`; this means that large content areas are cut off and cannot be scrolled. And `<paper-step>` doesn't counter this with any css to make it scrollable instead.

**Comment by Zecat** [comment]
Thanks! Something bothers me about `overflow: auto` to `#slideshow`, the steps should have their own scroll area instead of sharing the same scroller element. It will avoid an ugly scroll jump at the end of the neon-animation when moving from a step that has been scroll to another and the steps will remember their scroll position. I think `overflow: auto; -webkit-overflow-scrolling: touch;` for `<paper-step>` will do the trick.

**Comment by hubgit** [comment]
This was closed by #18, but `@apply(--layout-scroll);` still needs to be applied to `paper-step`, so that it works in a horizontal stepper.
