### ISSUE TITLE
Horizontal paper-stepper with a dynamic height

### ISSUE THREAD

**Issue by benjaminrancourt** [Zecat/paper-stepper#70]
Hello,

Thanks for your component, it's really great!

Is it possible to use a horizontal paper-stepper with a dynamic height?
I have dynamic content inside a paper-step, so I don't know the final height...

I tried to adapt the code of v2.0-beta.5, but I have not yet succeeded...

It would be really nice if you could support that! :)

Thanks!

```
<paper-stepper>
	<paper-step label="Label 0" editable>
		<div style="background-color: red; height: 500px; width: 100%;"></div>
	</paper-step>
	
	<paper-step label="Label 1" optional editable>
		<div style="background-color: green; height: 670px; width: 100%;"></div>
	</paper-step>
	
	<paper-step label="Label 2" optional editable>
		<div style="background-color: blue; height: 800px; width: 100%;"></div>
	</paper-step>
</paper-stepper>
```
```
:host {
	/* Vertical: no problem */
	--paper-vertical-step-max-height: none;

	/* Horizontal: not working :( */
	--paper-stepper-horizontal-opened-height: auto;
	--paper-stepper-horizontal-opened-max-height: none;
}
```

**Comment by Zecat** [comment]
Hi,

No, sorry, by design the stepper can't stretch to its children because, in horizontal layout, steps are absolute positioned.

I know it's a real problem, so I'm working on a completely new layout, fully customizable with templates and 2.0 compatible. It's early released on `hybrid-modular-prototype` branch where your issue is fixed.

If it can help you right now, you can test it and give me your feedback.

Be aware that it's work in progress, many css variables are not working and functionalities are lightened (no linear attribute, saved and disabled attributes must be me manually set on steps, no buttons, removed methods...). It is more flexible but requires a bit more configuration. Soon I'll work on documentation and demo, ask me for any question!

**Comment by benjaminrancourt** [comment]
Hi,

Thanks for your quick reply, I was able last week to give a try to this second branch.

As you said, it's effectively working on your component demo page. Unfortunately, it was not perfectly working on our Polymer 1.9.2 application : there was a error (see below) and the content of my paper-steps was not displayed.

So, I found a workaround for now by displayed only the progress section with the selected attribute and some dom-if.

```
<paper-stepper selected="{{selected}}">
  <paper-step label="Label 0"></paper-step>
  <paper-step label="Label 1"></paper-step>
</paper-stepper>

<template is="dom-if" if="[[equal(selected, 0)]]">
  Content for the step 0
</template>
```

I will give it a second try as soon as we update our application to Polymer 2.0.1.

Thanks!

> paper-stepper.html:317 Uncaught TypeError: Cannot set property 'selectedItem' of undefined at HTMLElement._forwardParentProp (paper-stepper.html:317) at HTMLTemplateElement.template._forwardParentProp (polymer.html:4363) at HTMLTemplateElement.<anonymous> (polymer.html:4374) at HTMLTemplateElement._functionEffect (polymer.html:1598) at HTMLTemplateElement._effectEffects (polymer.html:1448) at HTMLTemplateElement._propertySetter (polymer.html:1432) at TemplateInstance.__setProperty [as __setPropertyOrig] (polymer.html:1441) at TemplateInstance.__setPropertyImpl [as __setProperty] (polymer.html:4292) at TemplateInstance._applyEffectValue (polymer.html:1924) at TemplateInstance._annotationEffect (polymer.html:1587)

**Comment by benjaminrancourt** [comment]
I close this issue as we chose to create a new custom element to answer your needs. Thanks.
